### ISSUE TITLE
Need to refactor configuration file syntax.

### ISSUE THREAD

**Issue by jason-dour** [jason-dour/hugo-preproc#5]
https://github.com/jason-dour/hugo-preproc/blob/d8c8b316db148c0da721373ec4269f8c35730248/README.md#L40

**Comment by jason-dour** [comment]
Propose the following:

``` yaml
git:
  - path: path/to/repo
    processors:
      - mode: [ head | each | all ]
        file: path/to/outputfile
        template: "template string"
  - path:
    processors:
      - mode: [ head | each | all ]
        file: path/to/outputfile
        template: "template string"
exec:
  - path: path/to/search
    pattern: *.md
    command: "echo {{ . }}"
```

Allows for:
* Multiple repositories
  * Hugo publication pipelines containing multiple repos may be rare, but I already have one such case.
* Multiple actions per repository
* Moves Git mode from key to value, simplifies parsing and sanity checking.
* Clarifies "processors" as "exec" handlers.
* Each handler type starts as an array (git, exec).
